export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_ALERT_LOADING = 'GET_ALERT_LOADING';
export const GET_ALERT_SUCCESS = 'GET_ALERT_SUCCESS';
export const GET_ALERT_FAIL = 'GET_ALERT_FAIL';
export const GET_ALERT_REFRESHING= 'GET_ALERT_REFRESHING';

export const GET_MYLIST_LOADING = 'GET_MYLIST_LOADING';
export const GET_MYLIST_SUCCESS = 'GET_MYLIST_SUCCESS';
export const GET_MYLIST_FAIL = 'GET_MYLIST_FAIL';
export const GET_MYLIST_REFRESHING= 'GET_MYLIST_REFRESHING';

export const MYLIST_EXECUTE_LOADING= 'MYLIST_EXECUTE_LOADING';
export const MYLIST_EXECUTE_SUCCESS= 'MYLIST_EXECUTE_SUCCESS';
export const ADD_ALERT_TO_MYLIST= 'ADD_ALERT_TO_MYLIST';
export const CLEAR_MYLIST= 'CLEAR_MYLIST';



export const ADD_ALERT_LOADING = 'ADD_ALERT_LOADING';
export const ADD_ALERT_SUCCESS = 'ADD_ALERT_SUCCESS';
export const ADD_ALERT_FAIL = 'ADD_ALERT_FAIL';

export const ADD_SERIES = 'ADD_SERIES';

export const CREATE_ALERT_LOADING = 'CREATE_ALERT_LOADING';
export const CREATE_ALERT_SUCCESS = 'CREATE_ALERT_SUCCESS';
export const CREATE_ALERT_FAIL = 'CREATE_ALERT_FAIL';

export const DEL_ALERT_LOADING = 'DEL_ALERT_LOADING';
export const DEL_ALERT_SUCCESS = 'DEL_ALERT_SUCCESS';
export const DEL_ALERT_FAIL = 'DEL_ALERT_FAIL';

export const EDIT_ALERT_LOADING = 'EDIT_ALERT_LOADING';
export const EDIT_ALERT_SUCCESS = 'EDIT_ALERT_SUCCESS';
export const EDIT_ALERT_FAIL = 'EDIT_ALERT_FAIL';
